### ISSUE TITLE
Exercise 5, Task 3, Step 23 - Could not execute skill because Web Api skill response is invalid.

### ISSUE THREAD

**Issue by ewittrock-uwm** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#44] opened 2020-10-22 17:22 UTC
The cognitive search indexer is failing with the error:  **Could not execute skill because Web Api skill response is invalid.  Web Api response has invalid content type 'text/plain'. Expected 'application/json'**

Is there a place to specify the content type?

This is the full error:  
**This session was created from the following error:
Operation: Enrichment.WebApiSkill.#5
Message: Could not execute skill because Web Api skill response is invalid.
Details: Web Api response has invalid content type 'text/plain'. Expected 'application/json'
Document Key: localId=https%3a%2f%2fasastoreejw2020.blob.core.windows.net%2finvoices%2fTest%2fInvoice_6.pdf&documentKey=https%3a%2f%2fasastoreejw2020.blob.core.windows.net%2finvoices%2fTest%2fInvoice_6.pdf**

**Comment by codingbandit** [comment] 2020-10-25 17:18
Hi @ewittrock-uwm - I was not able to reproduce - the Postman content type should already be stored as application/json. I will add an additional note to the lab however for them to verify JSON is set as the content type.  Thank you!

![image](https://user-images.githubusercontent.com/3979478/97114032-81157400-16c4-11eb-94fe-dbdb491a1852.png)

**Comment by DawnmarieDesJardins** [comment] 2020-10-26 15:08
Closing issue with merge of PR #45

**Closed by DawnmarieDesJardins** 2020-10-26 15:08 UTC

**Comment by ekuipers** [comment] 2020-12-18 17:47
Some additional things to check I ran into when I got the same error when running the indexer:
1. Make sure that you save __init__.py in Visual Studio Code after adding the required changes and deploying it to Azure Function App.
2. Check all the values you substituted on a trailing space due to copy paste actions.
