### ISSUE TITLE
Exercise 6: UniqueIdentifier types are not supported in external tables

### ISSUE THREAD

**Issue by virshah24** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#23] opened 2020-07-22 15:48 UTC
Getting "UniqueIdentifier types are not supported in external tables" while creating "Sales" Temp View using Data Frame in the ML notebook.

**Comment by virshah24** [comment] 2020-07-22 16:03
Current workaround is to later column TransactionId from UniqueIdentfier to NVARCHAR(50), but the script on the lab needs that fixed. We do not need TransactionId at all it seems.

**Comment by codingbandit** [comment] 2020-07-22 20:22
Hi @virshah24 - could you clarify to me what cell in the notebook you are experiencing this issue? Thank you!

**Comment by timahenning** [comment] 2020-08-03 14:38
Hi @virshah24.  Can you clarify the cell in the notebook requested by Carey?  Otherwise, we will have to close this issue.

Thanks,

Tim

**Comment by virshah24** [comment] 2020-08-03 18:10
Cell 7 of "ASAMCW - Exercise 6 - Machine Learning" Notebook: 

Following code fails, as we created mcw.SaleSmall table with [TransactionId] [uniqueidentifier]  NOT NULL. It should have been [nvarchar](50)  NULL or something. 

%%spark
val df = spark.read.sqlanalytics("SQLPool01.wwi_mcw.SaleSmall") 
df.createOrReplaceTempView("sale")
display(df)

val df2 = spark.read.sqlanalytics("SQLPool01.wwi_mcw.Product") 
df2.createOrReplaceTempView("product")
display(df2)

**Comment by virshah24** [comment] 2020-08-03 18:11
I updated GitHub comments:
Cell 7 of "ASAMCW - Exercise 6 - Machine Learning" Notebook:
Following code fails, as we created mcw.SaleSmall table with [TransactionId] [uniqueidentifier] NOT NULL. It should have been nvarchar<https://github.com/microsoft/MCW-Azure-Synapse-Analytics-and-AI/issues/50> NULL or something.
%%spark
val df = spark.read.sqlanalytics("SQLPool01.wwi_mcw.SaleSmall")
df.createOrReplaceTempView("sale")
display(df)
val df2 = spark.read.sqlanalytics("SQLPool01.wwi_mcw.Product")
df2.createOrReplaceTempView("product")
display(df2)


﻿﻿﻿
Thanks,
Viral Shah
Cloud Solution Architect – Customer Success [Data & AI]
Office: 8000, Avalon Blvd., Suite 900 Alpharetta, GA 30009
viral.shah@microsoft.com<mailto:viral.shah@microsoft.com>
Direct:  (678) 629-5811 | Cell: (814) 504-8425
[cid:image001.jpg@01D6699F.E6361970]
﻿One Microsoft Way, Redmond, WA 98052 USA | Privacy Statement<http://go.microsoft.com/fwlink/?LinkId=248681>

Out of office Schedule:

None

[cid:image002.png@01D6699F.E6361970]

**Comment by codingbandit** [comment] 2020-08-12 14:21
I went through the lab up to this point once more, and I'm unable to reproduce this issue.

![image](https://user-images.githubusercontent.com/3979478/90026514-6581fc00-dc85-11ea-872b-d211d2b94b1b.png)
![image](https://user-images.githubusercontent.com/3979478/90026683-a2e68980-dc85-11ea-8751-8628b7ff939c.png)

**Comment by timahenning** [comment] 2020-08-14 12:05
Hi @virshah24,

Can you go through the lab again to verify you are still getting the error?

Tim

**Comment by DawnmarieDesJardins** [comment] 2020-08-17 22:34
Closing issue with no further contact.  Please reopen if you're still having trouble.

**Closed by DawnmarieDesJardins** 2020-08-17 22:34 UTC

**Comment by virshah24** [comment] 2020-08-18 19:04
I still don’t think it will work – as still see ‘uniqueidentifier’, for me changing this to ‘nvarchar’ worked in Ex 6 – as mentioned in the bug report/info.

[cid:image001.png@01D67570.D918B3B0]

﻿﻿﻿
Thanks,
Viral Shah
Cloud Solution Architect – Customer Success [Data & AI]
Office: 8000, Avalon Blvd., Suite 900 Alpharetta, GA 30009
viral.shah@microsoft.com<mailto:viral.shah@microsoft.com>
Direct:  (678) 629-5811 | Cell: (814) 504-8425
[cid:image002.jpg@01D67570.D918B3B0]
﻿One Microsoft Way, Redmond, WA 98052 USA | Privacy Statement<http://go.microsoft.com/fwlink/?LinkId=248681>

Out of office Schedule:

None

[cid:image003.png@01D67570.D918B3B0]
